import type { Metadata } from "next";

import { exo_2, inter } from "@/lib/font";
import Providers from "@/provider/provider";
import "@/utils/orpc/orpc.server";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo_2.variable} ${inter.variable} container mx-auto px-8 pt-6 antialiased lg:pt-10`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
